### ISSUE TITLE
Freeze in 1.02

### ISSUE THREAD

**Issue by ferforfight** [Kaldaien/TZF#11]
When I load the game and continue my saved game i run a bit and the game starts to freeze, i set up channels at 6 and the enablefix is on false.
(Im playing it on GTX 990. 16 ram and i7 3.6hz)
When the game is frozen is just the screen not the sound that continues, i need the ctrl+alt+sup to close it.
Any suggestion? anyone that got the same problem and fixed it?

Finally grats you guys with the work you're doing, you are amazing and thanks for this big effort

**Comment by drdaxxy** [comment]
Are you on the latest version (1.3) of the game?

Also, please post your log files (logs/d3d9.log and logs/tzfix.log).

**Comment by ferforfight** [comment]
Yes im playing on 1.03 and my screen supports 60 hz
this is the d3d9.log: 

11/19/2015 06:46:22.543: d3d9.log created
-----------------------------------------------------------------------------------
11/19/2015 06:46:22.559: >> (Tales of Zestiria.exe) <<
-----------------------------------------------------------------------------------
11/19/2015 06:46:22.559:  System Directory:           C:\Windows\SysWOW64
11/19/2015 06:46:22.559:  Loading default d3d9.dll:  (C:\Windows\SysWOW64\d3d9.dll)
-----------------------------------------------------------------------------------
11/19/2015 06:46:22.559: Loading user preferences from d3d9.ini... done!

11/19/2015 06:46:22.574:   * Loading Early Custom Import steam_api.dll... success!
11/19/2015 06:46:22.574:   * Loading Early Custom Import tzfix.dll... success!

11/19/2015 06:46:22.996: Initializing NvAPI:  Success

11/19/2015 06:46:23.339:  >> NVIDIA Driver Version: 358.91
11/19/2015 06:46:23.339:   * Number of Installed NVIDIA GPUs: 1 (0 are in SLI mode)

11/19/2015 06:46:23.339:   NvOptimusEnablement..................: UNDEFINED
11/19/2015 06:46:23.339:   AmdPowerXpressRequestHighPerformance.: UNDEFINED

11/19/2015 06:46:23.339: Importing Direct3DCreate9{Ex}...
11/19/2015 06:46:23.339: ================================
11/19/2015 06:46:23.339:   Direct3DCreate9:   65FE0A62h
11/19/2015 06:46:23.339:   Direct3DCreate9Ex: 65F8CCD5h
11/19/2015 06:46:23.339:  @ Loading Debug Symbols: done!
11/19/2015 06:46:23.542: === Initialization Finished! ===

11/19/2015 06:46:23.542:  [WMI] Spawning CPU Monitor...      tid=0x17a8
11/19/2015 06:46:23.635:  [WMI] Spawning Disk Monitor...     tid=0x1514
11/19/2015 06:46:23.729:  [WMI] Spawning Pagefile Monitor... tid=0x0bb0
11/19/2015 06:46:23.822:  [WMI] Spawning Process Monitor...  tid=0x14b0


11/19/2015 06:46:27.148: [!] Direct3DCreate9 (32) - [Calling Thread: 0x17dc]
11/19/2015 06:46:27.163:  Old VFTable entry for d3d9->CreateDevice: 65FA2E0Eh  (Memory Policy: Execute + Read-Only)
11/19/2015 06:46:27.163:  New VFTable entry for d3d9->CreateDevice: 5CFC4F40h  (Memory Policy: Execute + Read/Write)

11/19/2015 06:46:27.819: [!] Direct3DCreate9 (32) - [Calling Thread: 0x17dc]
11/19/2015 06:46:27.991: [!] IDirect3D9::CreateDevice (062207E0h, 0, 1, 000A0320h, 0x00000054, 0102942Ch, 01029468h) - [Calling Thread: 0x17dc]
11/19/2015 06:46:27.991:   >> Targeting 60 FPS - using 1:1 VSYNC; (refresh = 60 Hz)

11/19/2015 06:46:27.991:   Calling original function: (ret=S_OK)

11/19/2015 06:46:28.437:  Old VFTable entry for IDirect3DDevice9::Reset: 65FDF251h  (Memory Policy: Read/Write)
11/19/2015 06:46:28.437:  New VFTable entry for IDirect3DDevice9::Reset: 5CFC5D30h  (Memory Policy: Execute + Read/Write)

11/19/2015 06:46:28.437:  Old VFTable entry for IDirect3DDevice9::Present: 65FCA064h  (Memory Policy: Read/Write)
11/19/2015 06:46:28.437:  New VFTable entry for IDirect3DDevice9::Present: 5CFC62C0h  (Memory Policy: Execute + Read/Write)

11/19/2015 06:46:28.437:  Old VFTable entry for IDirect3DDevice9::CreateAdditionalSwapChain: 65F9E9A0h  (Memory Policy: Read/Write)
11/19/2015 06:46:28.437:  New VFTable entry for IDirect3DDevice9::CreateAdditionalSwapChain: 5CFC5E30h  (Memory Policy: Execute + Read/Write)

11/19/2015 06:46:28.437:  Old VFTable entry for IDirect3DDevice9::CreateTexture: 65FB5DDBh  (Memory Policy: Read/Write)
11/19/2015 06:46:28.437:  New VFTable entry for IDirect3DDevice9::CreateTexture: 5CFC5CB0h  (Memory Policy: Execute + Read/Write)

11/19/2015 06:46:28.437:  Old VFTable entry for IDirect3DDevice9::CreateRenderTarget: 65FD0127h  (Memory Policy: Read/Write)
11/19/2015 06:46:28.437:  New VFTable entry for IDirect3DDevice9::CreateRenderTarget: 5CFC5CA0h  (Memory Policy: Execute + Read/Write)

11/19/2015 06:46:28.437:  Old VFTable entry for IDirect3DDevice9::CreateDepthStencilSurface: 6603CD88h  (Memory Policy: Read/Write)
11/19/2015 06:46:28.437:  New VFTable entry for IDirect3DDevice9::CreateDepthStencilSurface: 5CFC5C90h  (Memory Policy: Execute + Read/Write)

11/19/2015 06:46:28.437:  Old VFTable entry for IDirect3DDevice9::UpdateTexture: 65FB46ABh  (Memory Policy: Read/Write)
11/19/2015 06:46:28.437:  New VFTable entry for IDirect3DDevice9::UpdateTexture: 5CFC5C60h  (Memory Policy: Execute + Read/Write)

11/19/2015 06:46:28.437:  Old VFTable entry for IDirect3DDevice9::SetRenderTarget: 65FC9E53h  (Memory Policy: Read/Write)
11/19/2015 06:46:28.437:  New VFTable entry for IDirect3DDevice9::SetRenderTarget: 5CFC5C80h  (Memory Policy: Execute + Read/Write)

11/19/2015 06:46:28.437:  Old VFTable entry for IDirect3DDevice9::SetDepthStencilSurface: 65FD108Fh  (Memory Policy: Read/Write)
11/19/2015 06:46:28.437:  New VFTable entry for IDirect3DDevice9::SetDepthStencilSurface: 5CFC5C70h  (Memory Policy: Execute + Read/Write)

11/19/2015 06:46:28.437:  Old VFTable entry for IDirect3DDevice9::EndScene: 65FA279Fh  (Memory Policy: Read/Write)
11/19/2015 06:46:28.437:  New VFTable entry for IDirect3DDevice9::EndScene: 5CFC5E20h  (Memory Policy: Execute + Read/Write)

11/19/2015 06:46:28.437:  Old VFTable entry for IDirect3DDevice9::SetViewport: 66079EF7h  (Memory Policy: Read/Write)
11/19/2015 06:46:28.437:  New VFTable entry for IDirect3DDevice9::SetViewport: 5CFC5D10h  (Memory Policy: Execute + Read/Write)

11/19/2015 06:46:28.437:  Old VFTable entry for IDirect3DDevice9::SetSamplerState: 65FA0A9Eh  (Memory Policy: Read/Write)
11/19/2015 06:46:28.437:  New VFTable entry for IDirect3DDevice9::SetSamplerState: 5CFC5D20h  (Memory Policy: Execute + Read/Write)

11/19/2015 06:46:28.437:  Old VFTable entry for IDirect3DDevice9::SetScissorRect: 6607A021h  (Memory Policy: Read/Write)
11/19/2015 06:46:28.437:  New VFTable entry for IDirect3DDevice9::SetScissorRect: 5CFC5CC0h  (Memory Policy: Execute + Read/Write)

11/19/2015 06:46:28.437:  Old VFTable entry for IDirect3DDevice9::SetVertexShader: 65FCBB5Eh  (Memory Policy: Read/Write)
11/19/2015 06:46:28.437:  New VFTable entry for IDirect3DDevice9::SetVertexShader: 5CFC5CD0h  (Memory Policy: Execute + Read/Write)

11/19/2015 06:46:28.437:  Old VFTable entry for IDirect3DDevice9::SetSetVertexShaderConstantF: 65FDD239h  (Memory Policy: Read/Write)
11/19/2015 06:46:28.437:  New VFTable entry for IDirect3DDevice9::SetSetVertexShaderConstantF: 5CFC5D00h  (Memory Policy: Execute + Read/Write)

11/19/2015 06:46:28.437:  Old VFTable entry for IDirect3DDevice9::SetPixelShader: 65FCBC2Ah  (Memory Policy: Read/Write)
11/19/2015 06:46:28.437:  New VFTable entry for IDirect3DDevice9::SetPixelShader: 5CFC5CE0h  (Memory Policy: Execute + Read/Write)

11/19/2015 06:46:28.437:  Old VFTable entry for IDirect3DDevice9::SetPixelShaderConstantF: 65FDD3B4h  (Memory Policy: Read/Write)
11/19/2015 06:46:28.437:  New VFTable entry for IDirect3DDevice9::SetPixelShaderConstantF: 5CFC5CF0h  (Memory Policy: Execute + Read/Write)

11/19/2015 06:46:28.448:  Old VFTable entry for IDirect3DSwapChain9::Present: 65F8781Fh  (Memory Policy: Execute + Read-Only)
11/19/2015 06:46:28.448:  New VFTable entry for IDirect3DSwapChain9::Present: 5CFC5F30h  (Memory Policy: Execute + Read/Write)

11/19/2015 06:48:13.405: [!] IDirect3DDevice9::Reset (0C7F9580h, 0102942Ch) - [Calling Thread: 0x17dc]
11/19/2015 06:48:13.405:   >> Targeting 60 FPS - using 1:1 VSYNC; (refresh = 60 Hz)

11/19/2015 06:48:13.405:   Calling original function: (ret=S_OK)

And this is the tzfix.log:

11/19/2015 06:46:22.652: tzfix.log created
11/19/2015 06:46:23.417:  * Target FPS is 60, halving simulation speed to compensate...
11/19/2015 06:46:28.437:  % Caught D3D9 Swapchain :: Fullscreen=True
11/19/2015 06:46:28.437:  * Changing Aspect Ratio from 1.777778 to 1.777778
11/19/2015 06:46:28.510:   # Found window in 5.6 seconds, installing keyboard hook...
11/19/2015 06:46:28.510:   * Installed keyboard hook for command console... 1 try (0 ms!)
11/19/2015 06:47:06.391:  * Disabling 60 FPS -- Bink Video Opened
11/19/2015 06:47:06.424:  * Restoring 60 FPS -- Bink Video Closed
11/19/2015 06:47:06.428:  * Disabling 60 FPS -- Bink Video Opened
11/19/2015 06:47:09.240:  * Restoring 60 FPS -- Bink Video Closed
11/19/2015 06:48:13.405:  % Caught D3D9 Swapchain :: Fullscreen=True

**Comment by Kaldaien** [comment]
Judging from your log, the last thing you did was alt+tab in/out. If you didn't do that and the D3D device was reset there's something else weird going on.

It never catches your swapchain creation either, or there would be lines about RTSS in d3d9.log. So it looks like you have some third-party overlay software causing problems.
