### ISSUE TITLE
Progress/collision bug in Lastonbell at 60 FPS

### ISSUE THREAD

**Issue by drdaxxy** [Kaldaien/TZF#12]
Has been reported a few times, I have just been able to verify this:

When first entering Lastonbell, there's a scripted sequence in which an NPC walks to a place and you have to follow him. However, at 60 FPS, said NPC gets stuck on stairs, softlocking the game.

At double tick duration (i.e. double-real-time speed at 60 FPS, or real-time speed at 30), the problem does not occur, even with TZFix installed.

Save file can be found at http://62.210.137.144/Save054.to12sav

**Comment by Kaldaien** [comment]
Nice save file, this helps test skits as well.

<hr>

A couple of possible automated solutions exist and I know the basic cause of this problem.

It is caused when this event manages to spawn the priest and his companion across two different frames. When this happens, a race condition is created. His buddy finishes his scripted sequence too early and the priest gets stuck in a weird state.

If `TargetFPS` is set to **30** *before* the event is loaded, everything plays out normally. Or if `TickScale` is temporarily boosted when the priest is stuck on the stairs the event eventually ends.

<hr>

I found a function in the binary that's apparently responsible for staging scripted events and played with the timer value it uses but I have not been able to change the results at all. The address I located is at:

&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;**0x5638E0**

But I am completely worthless when it comes to binary modification so I'm probably doing something wrong. Isolating the functions responsible for cutscene camera movement and this particular scripted event would go a long way towards making 60 FPS glitch-free.

**Comment by Kaldaien** [comment]
A slightly modified version of 1.1.5 is in testing with a temporary fix for this problem. It limits FPS to 30 during cutscenes. It's 100% effective, but I'm leaving this open because I would like to pinpoint only the cutscenes that need this drop in framerate rather than applying it to everything.

**Comment by drdaxxy** [comment]
I have the priest working perfectly now.

High-level overview of the solution:

- Zestiria stores its assets in a simple proprietary archive. A QuickBMS script to unpack it is easily found on Google.

- In the folder `LUABR` inside that archive are tons of Lua scripts (compiled to bytecode for Lua 5.1.4).

- Through various means (matching with message strings, watching the Lua VM, etc.) one can discover the script for the priest sequence is called `MEP_100_130_010_PF_Script` - the extractor doesn't produce meaningful filenames, but that name is also a symbol inside the script file, so simply searching for this string in the `LUABR` folder will get you there.

- By manual comparison with a precompiled lua5.1.dll I have found the function in Zestiria's executable currently living at `0x85FE30` to be [luaL_loadbuffer](http://pgl.yoyo.org/luai/i/luaL_loadbuffer). *Every* script the game uses gets loaded here, and we can compare `name` to the one that interests us, and edit or replace `buffer`/`sz` on a match.

- What causes the bug is the priest being unable to find a path over the edge of the stairs - at 30 FPS, collision detection is slow enough not to notice, but at 60, it checks too often to let the priest pass.

- Decompiling the script tells us that it makes the priest walk to points (-826, 20, 185) -> (2196, -173, -66) -> (2262, 31, 552) - in that order.

- **Moving the priest a little further away from the edge - say, -> (-826, 20, 185) -> (2230, -173, -66) -> (2300, 31, 552) - will allow him to pass at no further consequence (this doesn't look any more weird, and the waypoints are just that - waypoints - this will not move the priest off the ground even though these points are above the slope/stairs).**

- Recompiling the script unfortunately does not yield the exact same output, but recompiling an unmodified version *and* a modified version, then diffing the binaries and hex-editing the same changes inside the game's memory while execution is paused at a breakpoint on `luaL_loadbuffer` works.

- I have also attempted only recompiling the script once, then copying the output to freshly allocated memory and changing `buffer` to point there (and `sz` to match the new filesize), but the script doesn't execute properly then. I'm not sure why - perhaps the recompiled script is just broken, perhaps I messed up trying to change the parameters. If I had to make more sophisticated changes, I'd try a different Lua decompiler (or a Lua (dis)assembler).

I'm not sure how we want to integrate this though. MinHook only lets us hook exported functions, right? We could manually place a jump at the beginning of `luaL_loadbuffer` to a `__declspec naked` function, but it's slightly less clean.

**Comment by drdaxxy** [comment]
Alright, should be fixed with 6bda928.

Note: I haven't been able to test this at 30 FPS since I can't figure out how to turn off 60 with the current TZFix. Thus I'm not closing this yet; that needs to be tested then merged into master and released first.

It turns out there's no Lua decompilers or (dis)assemblers that produce output that actually works (for this script, anyway), so the patched bytecode is just a hex edit.

**Comment by drdaxxy** [comment]
Tested at 30 FPS now, works.
