### ISSUE TITLE
1.1.3 issues

### ISSUE THREAD

**Issue by chrcoluk** [Kaldaien/TZF#19]
Ok so you have a copy here.

On my windows 7 system.

spec

64bit
haswell 4670k (clocked at 4.3ghz)
1600mhz 16gig ddr3 ram
nvidia gtx 970 modded bios allowing up to 1481mhz boost clock

tales of zestiria 1.4
30fps configured
soundfix disabled

On this system 0.21 and 0.51 have no stuttering at all, work perfect using nvidia frame pacing.
Without HPET the newer versions have noticeble stuttering which isnt as bad as the plain namco code but is definitly not as good as 0.21 and 0.5.1.  It seems enabling HPET makes your newer dll work much better and stuttering is much better but still not perfect like the older versions.

No RTSS based OSD works. But non RTSS based such as gedosato works (prior to 1.1.3 but on 1.1.0 works)
Prior to 1.1.3 gedosato worked fine but now if enabled the game closes itself 1 second after launch..

**Comment by Kaldaien** [comment]
Have you tried setting half-refresh VSYNC using TZT.exe? Doing that, and setting Target to 31 in tzfix.ini should give you stutter free operation at 30 FPS.

**Comment by Kaldaien** [comment]
I'd ask that you give [1.1.5 Test0](https://github.com/Kaldaien/TZF/releases/tag/tzf_115-test0) a try. Grab the files from 1.1.4 and then replace tzfix.dll with the one from that release.

**Comment by Kaldaien** [comment]
I will not be bringing NVIDIA's framerate limiter code back, ever. It is such an unreliable turd, I want nothing to do with it. You can stick with version 0.2.1 if you for some reason need it.

**Comment by chrcoluk** [comment]
No worries, was just reporting as requested :)

Given cpu based limiting is too stuttery for me and unreliable, I will stick to 0.2.1 or 0.5.1 thanks.
