### ISSUE TITLE
GetSystemTimePreciseAsFileTime Error upon Game Start

### ISSUE THREAD

**Issue by LionCerieals** [Kaldaien/TZF#20]
Hi there!
So I was trying to install your mod and I put all the files that were in the folder into the Tales of Zestiria folder and when I start the .exe file I get an error message which says: "GetSystemTimePreciseAsFileTime could not be found in the KERNEL32.dll."
Do you guys have any idea how I can fix this? I've searched for an hour on Google but I couldn't find anything. :(

**Comment by drdaxxy** [comment]
What version of Windows are you running?

**Comment by Kaldaien** [comment]
It checks Windows version before using that. It must be Windows 6.3 or greater. That's equivalent to Windows 8.

**Comment by drdaxxy** [comment]
You mean 6.2.

And this is exactly why I ask - this looks like OP is *not* on 8+, and the check's not working.

**Comment by Kaldaien** [comment]
No, I mean 6.3 It's a Windows Server 2012 / Windows 8.1 feature. 8.1 is a free upgrade, so I consider all 8 users as 8.1 users.
