### ISSUE TITLE
Can not go above 30 fps

### ISSUE THREAD

**Issue by norbigomba** [Kaldaien/TZF#21]
Dear developper!

I was try v1.1.1 and v1.3.0 version of this fix, but somehow its not working for me.
I m using windows 10, a GTX 970, Xeon E5-1620 and 16 GB ram.
I m running this two file as administrator:
Tales of Zestiria.exe
TZT.exe
I was tryed everything what can i think for: Bordeless window, different dlls, different settings.
I also installed the RivaTuner thing to. But its show 30 fps along side with fraps.
But nothing seems to work.
![pic](https://cloud.githubusercontent.com/assets/16865484/12537077/d4a4c060-c2b6-11e5-9ff9-b11232bfcd77.jpg)
 
![pic2](https://cloud.githubusercontent.com/assets/16865484/12537099/543c5c98-c2b7-11e5-8736-26e12af5706f.jpg)

**Comment by drdaxxy** [comment]
Sorry, pirated versions of the game are not supported.

**Comment by Malikgrant777** [comment]
you can use it for pirated games? You just use the tzfix and tzfix.dll files from the tzfix folder then use the d3d9 and d3d9.dll files from the ddfix folder or ddfix_002 folder. Witch ever works for you.
