### ISSUE TITLE
Game won't start on Windows 10 Surface Book

### ISSUE THREAD

**Issue by gajewsk2** [Kaldaien/TZF#22]
Just got a fancy new laptop and have spent 2 days trying to get it to work. Saw your post here: https://steamcommunity.com/app/351970/discussions/0/490123938431647535/
and figured I'd try asking if you could help diagnose the issue with your log files. Issue is, it won't event write the log files. Right now I get `SteamApi_Init: failed, please restart Steam`... yadayada. On my Windows 8 machine, I can laumch steam or steamlite and it runs just fine then with your patch. But on my windows 10 machine, it just never launches. I've tried deleting my log files with the TZT.exe method, running both steam( steam lite usually) and zestiria as admin, and tried windows 7 compatibility mode. Any ideas?

**Comment by Kaldaien** [comment]
Steam has broken a lot of games recently with some multi-threading changes to SteamAPI. I believe this is to blame here, I'll release a version that doesn't use SteamAPI over the weekend to see if that fixes it.

**Comment by gajewsk2** [comment]
You are a legend.

**Comment by Kaldaien** [comment]
Can you grab the d3d9.dll bundled in my latest project and tell me if anything changes?

https://github.com/Kaldaien/AgDrag/releases/tag/agdrag_011

If not, there's a new feature in that version where if you set Silent=true in Steam.Logging, it disables SteamAPI completely.

**Comment by gajewsk2** [comment]
AgDrag.zip's d3d9.dll still said the same error as before `SteamApi_Init: failed etc.`. Where can i disable set the flag; not seeing Steam.Logging? 

My steam_api.log says `01/31/2016 21:17:54.539:  * Game Installed Unknown Callback (Class=700, Id=3)` btw

**Comment by Kaldaien** [comment]
In d3d9.ini

`[Steam.Log]
Silent=false`

Change that to **true**


That option has always existed in the ini file, but it used to only control whether steam_api.log was written. In later versions of my d3d9.dll, it controls whether Steam related features are used or not.

**Comment by gajewsk2** [comment]
Alright,  set it to true,  saved, ran as admin and it still gave me the error. Same exact issue as here: might try giving all the steps a go again: https://steamcommunity.com/app/351970/discussions/0/490123727975365775/

**Comment by gajewsk2** [comment]
Corrupted files, fixed after reinstalling steam and the game
