### ISSUE TITLE
README is useless

### ISSUE THREAD

**Issue by Aerdan** [Kaldaien/TZF#23]
The present `README.md` should actually be `COPYING.md` or `LICENSE.md` and something that actually describes what people are expected to do should be in `README.md`

**Comment by GhettoGirl** [comment]
I agree to this one.
This is obviously __NOT__ a ```README.md```

**Comment by Kaldaien** [comment]
It is a README, the documentation is on Steam, and that's where it is always going to stay with my projects. It'd be a complete and utter waste of my time to write documentation in two places.

This is just where source code is stored, that's all you need to know.

**Comment by Kaldaien** [comment]
https://steamcommunity.com/sharedfiles/filedetails/?id=542500356

**Comment by Aerdan** [comment]
As a counterpoint: You could put the documentation here and then the Steam guide can just link here. And then there wouldn't be a need to tell people to link to the Steam guide only and not this repo. Moreover, by putting the documentation here you can split it over multiple pages for readability due to Github's wiki support, as well as have on-site images for clarification and demonstration purposes.
