### ISSUE TITLE
totally useless software 

### ISSUE THREAD

**Issue by yukapuka123** [Kaldaien/TZF#24]
your software sucks, nobody wants to use your useless software

**Comment by AndreDVJ** [comment]
Nice try dude. I still cannot believe you came all the way to this repository to give an even more useless  feedback. You for sure know how to waste your time and energy. Please close this issue.

**Comment by rperez22** [comment]
I think at Kaldaien/TZF they do pretty good work, I am not very experienced in software development and I can tell this. Keep at guys, fixing Tales of Zesteria made the game playable for me and I loved it, you guys rock!

**Comment by Kaldaien** [comment]
I am sorry you feel that way, but this doesn't seem like an issue I can help you with. I would suggest you don't generalize in the future. Plenty of people find this project useful.

**Comment by yukapuka123** [comment]
hey look i think i just made your useless code a little more popular

**Comment by yukapuka123** [comment]
https://www.youtube.com/watch?v=vlgbgRaeAfU

title of video "TZF sucks"
