### ISSUE TITLE
Controls problem

### ISSUE THREAD

**Issue by Matyouloid** [Kaldaien/TZF#27]
When i use my ds4 controller the game works fine but it automatically switches to multiplayer. In the command menu (on the title screen) i am able to choose commands for p1 and p2. The same goes for when i actually play the game, because when i open the in game menu there is a p1 tag near my main character and a p2 tag on one of the others. This also leads to the awful multiplyaer combat camera and many other issues, like the secondary character frozen in place, unable to move it, etc.
If i uninstall the mod, i can use my ds4 just fine and i have only p1. Please help me

**Comment by Kaldaien** [comment]
The mod doesn't have anything to do with controller input, but I would suggest editing your config file and setting input for p2, p3 and p4 to -1.

You probably have DS4Windows or something like that running, which presents an XInput controller in addition to the DirectInput controller that the DS4 natively operates as.
