### ISSUE TITLE
Anime FMV subtitles are severely out of sync

### ISSUE THREAD

**Issue by Bwin4L** [Kaldaien/TZF#5]
Hi, and thank for this wonderful fix.
I'm playing the game with JP audio and subtitles on, using the default settings in both .ini files, 1920x1080@60Hz.
It turns out the subtitles in FMVs (those anime cutscene videos) are very out of sync.
It seems like they're playing twice as slow (haven't confirmed the exact rate).
As a result I'm forced to skip the cutscene when it's over because the subs still haven't finished playing.
The game resumes fine afterwards.

**Comment by Kaldaien** [comment]
I have confirmed this, and even after pinpointing the exact instruction that limits render framerate and not touching timing in any other game system the subtitles are out of synch. I believe the answer lies somewhere with Bink, but I have never worked with that middleware before except for some really awful hacks I had to do to make it play audio in this game with my original 7.1 channel audio fix.

I really wish Bink would go away :-\

**Comment by Kaldaien** [comment]
I BELIEVE, since I know that there is a unique vertex shader that's active when Bink videos are playing, the code that cuts all timing speed in half can be temporarily disabled. I will look into this and hopefully have an answer soon.

**Comment by drdaxxy** [comment]
We can detour BinkOpen and set our tickrate multipliers back to 2. When a cutscene is over, the game sets them back to 1 for us (with our previous patches). I have verified this works, just not put it in code yet.

**Comment by Kaldaien** [comment]
That did the trick.
