### ISSUE TITLE
Visual glitch when camera switches positions abruptly during in-engine cutscenes

### ISSUE THREAD

**Issue by Bwin4L** [Kaldaien/TZF#6]
Hi,
Using the default .ini settings.
During in-engine rendered cutscenes, there's a garbage frame appearing in between abrupt camera position changes.

**Comment by Kaldaien** [comment]
Yeah, I have noticed this too. This is something I may be able to fix, but it's going to be a bugger without the actual source code ;)

**Comment by Kaldaien** [comment]
1.1.6 / 1.2.0 has a fix for this. It's not a pretty one, but it's 100% effective; cap framerate during cutscenes to 30. _This may be re-opened in the future if I decide to try and solve this while the limit stays 60 FPS._
