### ISSUE TITLE
Game sometimes freezes when trying to switch areas

### ISSUE THREAD

**Issue by Bwin4L** [Kaldaien/TZF#7]
Hi,
Using default .ini settings.
To be honest, I'm not 100% sure this is related to this fix, but since I had never encountered these before using TZF, I'll post this issue anyway.
The game sometimes completely freezes when trying to change areas. The music continues playing, though. Weirdly enough, having the game freeze somewhere doesn't mean it will freeze again the next time you try changing areas at the same place.
You can't do anything, opening the task manager doesn't work either because the game stays on top and the Windows Task Manager isn't visible.
Only thing that worked was force closing the game using good ol' SuperF4.

**Comment by Kaldaien** [comment]
Ah, that's no good. I'll look into this as well. I think that some changes I brought over from my work on Fallout 4 are corrupting memory. I need to spend some quality time code reviewing this stuff.

**Comment by Kaldaien** [comment]
With hooking stability fixes, this is likely fixed or at least lessened. Certain subsystems such as Steam were not returning to the proper memory addresses and causing really subtle and hard to track problems.

**Comment by Kaldaien** [comment]
No feedback; I assume that is because the issue has not popped up since.
